import type { Metadata } from "next"
import { Geist, Lora } from "next/font/google"
import "./globals.scss"
import Header from "@/widgets/header"
import { ProgressBarProvider } from "react-transition-progress"

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
})

const lora = Lora({
	variable: "--font-lora",
	subsets: ["latin"],
	weight: ["700"],
	style: ["italic"],
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={`${geistSans.className} ${lora.variable} antialiased`}>
				<ProgressBarProvider>
					<div className='flex flex-col gap-y-36 bg-background mx-auto pt-8 border-r border-l max-w-[1100px]'>
						<Header />
						{children}
					</div>
				</ProgressBarProvider>
			</body>
		</html>
	)
}
